name: ❓ Question
description: Question about application, configuration or code
title: "[Question]: "
labels: ["issue • question"]
assignees:
  - andyone

body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]  
        > Before you open an issue, search GitHub Issues for a similar question. If so, please add a 👍 reaction to the existing issue.

  - type: textarea
    attributes:
      label: Question
      description: Detailed question
    validations:
      required: true

  - type: textarea
    attributes:
      label: Module version info
      description: Output of `grep 'github.com/essentialkaos/go-confluence' go.sum` command
      render: shell
    validations:
      required: true
